definitions:
  handlers.BrandResponseModel:
    properties:
      Message:
        type: string
      isSuccess:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/brand/{id}:
    post:
      consumes:
      - application/json
      description: Bu endpoint yeni bir marka ekler
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.BrandResponseModel'
      summary: Marka ekle
swagger: "2.0"
